# Generated by Django 5.0.4 on 2025-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], default='customer', max_length=10),
        ),
    ]
