# Generated by Django 5.0.4 on 2025-03-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
