# Generated by Django 5.1.7 on 2025-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_job_worker_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='time_preference',
            field=models.CharField(choices=[('Now', 'Now'), ('Later', 'Later')], default='Now', max_length=20),
        ),
    ]
