# Generated by Django 5.1.7 on 2025-04-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
    ]
