# Generated by Django 5.1.7 on 2025-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
